site_name: Tina Framework
theme:
  name: material
  favicon: "api/media/IconBranding.png"
  logo: "api/media/DocsAccess.png"
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/AetherInteractiveLtd/Tina
repo_name: Aether/Tina

plugins:
  - tags
  - blog:
      blog_dir: pages/blog
      enabled: true
      post_date_format: full
      post_url_date_format: yyyy
      post_url_format: "{date}/{slug}"
      authors: true

markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - def_list
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
nav:
  - Home: "pages/index.md"

  - API:
      - "Tina": "api/modules.md"

      - ECS:
          - "Component": "api/lib_ecs_component.md"
          - "Observer": "api/lib_ecs_observer.md"
          - "Query": "api/lib_ecs_query.md"
          - "System": "api/lib_ecs_system.md"
          - "World": "api/lib_ecs_world.md"

  #   - 'Getting Started': 'api/api_docs.md'
  #   - 'API Detail': 'api/coverage.md'
  #   - 'Tina': 'api/tina.md'
  #   - 'Condition': 'api/condition.md'
  #   - 'Process': 'api/process.md'
  #   - 'EventEmitter': 'api/event_emitter.md'
  #   - 'EventListener': 'api/event_listener.md'
  #   - ECS:
  #     - 'Component': 'api/ecs/component.md'
  #     - 'Query': 'api/ecs/query.md'
  #     - 'System': 'api/ecs/system.md'
  #     - 'World': 'api/ecs/world.md'
  #   - Extras:
  #     - 'api/types/manifest.md'

  - Tina Guide:
      - "The Philosophy": "pages/intro/tina/philosophy.md"
      - "Getting Started": "pages/intro/tina/start.md"
      - "Main Features": "pages/intro/tina/core.md"

      - Lib:
          - "Events": "pages/intro/tina/libraries/events.md"
          - "Conditions": "pages/intro/tina/libraries/conditions.md"
          - "Processes": "pages/intro/tina/libraries/processes.md"

      - ECS:
          - "Entity Component System": "pages/intro/tina/ecs/ecs.md"
          - "Design Motivation": "pages/intro/tina/ecs/design.md"
          - "The Future": "pages/intro/tina/ecs/future.md"
          - "Snippets": "pages/intro/tina/ecs/vs-code-snippets.md"
          - "Best Practices": "pages/intro/tina/ecs/best-practices.md"

      - "Networking": "pages/intro/tina/libraries/net/net.md"

  - Style Guide: "pages/intro/styleguide.md"

  - Blog: "pages/blog/index.md"
